name: 'Hugo Algolia Uploader'
description: 'Upload your hugo algolia uploader.'

branding:
  icon: upload-cloud
  color: purple

inputs:
  app_id:
    description: 'Application ID of Algolia'
    required: true
  admin_key:
    description: 'Admin API Key of Algolia'
    required: true
  index_name:
    description: 'Index name of Algolia'
    required: true
  index_name_separator:
    description: 'Index name separator of Algolia'
    default: "_"
    required: false
  index_file_directory:
    description: 'Index file directory'
    default: "public"
    required: false
  index_file_name:
    description: 'Index file name'
    default: "index.json"
    required: false
  index_languages:
    description: 'Index i18next language codes'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'